version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: kworti-mongo
    hostname: kworti-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./db:/data/db
    ports:
      - '27017:27017'
