version: '2.4'
services:
 mysql:
  container_name: mysqlDB
  image: mysql:latest
  volumes:
   - ./db-data/db:/var/lib/mysql
  ports:
   - '3001:3306'
  environment:
    MYSQL_DATABASE: '${MSQL_DB}'
    MYSQL_USER: '${MSQL_USER}'
    MYSQL_PASSWORD: '${MSQL_PASSWORD}'
    MYSQL_ROOT_PASSWORD: '${MSQL_PASSWORD}'