version: '2.4'
services:
 mysql:
  container_name: mysqlDB
  image: mysql:latest
  volumes:
   - ./db-data/db:/var/lib/mysql
  ports:
   - '3306:3306'
  hostname: mysqlDB
  environment:
   MYSQL_DATABASE: ${DB_NAME}
   MYSQL_USER: ${DB_USER}
   MYSQL_PASSWORD: ${DB_PASS}
   MYSQL_ROOT_PASSWORD: ${DB_PASS}