import Head from 'next/head';
import { ReactElement } from 'react';
import AdminDashboard from '../components/admin/AdminDashboard';
import AdminLayout from '../components/admin/AdminLayout';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<AdminDashboard />
			</main>
		</div>
	);
}

Home.getLayout = function getLayout(page: ReactElement) {
	return <AdminLayout>{page}</AdminLayout>;
};
